import React, { useState } from 'react';
import { translateText } from '../services/geminiService';
import { Source } from '../types';

interface AnswerSectionProps {
  query: string;
  answer: string;
  sources: Source[];
  relatedTopics?: string[];
  onTopicClick?: (topic: string) => void;
}

export const AnswerSection: React.FC<AnswerSectionProps> = ({ query, answer, sources, relatedTopics, onTopicClick }) => {
  const [isPlaying, setIsPlaying] = useState(false);
  const [displayedAnswer, setDisplayedAnswer] = useState(answer);
  const [isTranslating, setIsTranslating] = useState(false);
  const [currentLang, setCurrentLang] = useState('English');

  const handleSpeak = () => {
    if ('speechSynthesis' in window) {
      if (isPlaying) {
        window.speechSynthesis.cancel();
        setIsPlaying(false);
        return;
      }

      const utterance = new SpeechSynthesisUtterance(displayedAnswer);
      utterance.rate = 0.95; 
      utterance.pitch = 1;
      utterance.onend = () => setIsPlaying(false);
      
      const voices = window.speechSynthesis.getVoices();
      const preferredVoice = voices.find(v => v.name.includes('Google') || v.name.includes('Samantha'));
      if (preferredVoice) utterance.voice = preferredVoice;

      window.speechSynthesis.speak(utterance);
      setIsPlaying(true);
    }
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(displayedAnswer);
      alert('Copied to clipboard');
    } catch (err) {
      console.error('Failed to copy', err);
    }
  };

  const handleExportMarkdown = () => {
    const markdown = `
# ${query}

## Answer
${displayedAnswer}

## Sources
${sources.map(s => `- **${s.book} ${s.chapterVerse}**: ${s.translation}`).join('\n')}

---
*Generated by Vedabase RAG AI*
    `;
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `vedabase-inquiry-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleTranslate = async (lang: string) => {
    if (lang === currentLang) return;
    setIsTranslating(true);
    const translated = await translateText(answer, lang);
    setDisplayedAnswer(translated);
    setCurrentLang(lang);
    setIsTranslating(false);
  };

  return (
    <div className="w-full animate-fade-in mb-16">
        <div className="relative">
           
           <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-full bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center shadow-lg shadow-indigo-200">
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="white" className="w-4 h-4">
                        <path d="M12 2a10 10 0 1 0 10 10A10 10 0 0 0 12 2Zm0 18a8 8 0 1 1 8-8 8 8 0 0 1-8 8Z" opacity=".5"/>
                        <path d="M12 6a6 6 0 1 0 6 6 6 6 0 0 0-6-6Zm0 10a4 4 0 1 1 4-4 4 4 0 0 1-4 4Z"/>
                      </svg>
                  </div>
                  <h3 className="font-serif text-2xl font-medium text-slate-900">
                    Synthesis
                  </h3>
              </div>
              
              <div className="flex items-center gap-2">
                 <button 
                  onClick={handleSpeak}
                  className={`
                    flex items-center gap-2 px-4 py-1.5 rounded-full transition-all border text-xs font-bold uppercase tracking-wide
                    ${isPlaying 
                      ? 'bg-indigo-50 border-indigo-200 text-indigo-600' 
                      : 'bg-white border-slate-200 text-slate-500 hover:border-indigo-200 hover:text-indigo-600'
                    }
                  `}
                >
                   {isPlaying ? 'Stop' : 'Listen'}
                </button>
              </div>
           </div>
           
           <div className={`prose prose-xl prose-slate max-w-none transition-opacity duration-300 ${isTranslating ? 'opacity-50' : 'opacity-100'}`}>
             <p className="text-slate-800 leading-relaxed font-normal">
                {displayedAnswer}
             </p>
           </div>
           
           {/* Actions Toolbar */}
           <div className="flex flex-wrap items-center justify-start mt-8 gap-3 border-t border-slate-100 pt-6">
              
              <button 
                onClick={handleCopy}
                className="flex items-center gap-2 px-3 py-2 rounded-lg bg-white border border-slate-200 hover:bg-slate-50 hover:border-indigo-200 text-slate-600 transition-all text-sm font-medium"
                title="Copy to Clipboard"
              >
                 <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 17.25v3.375c0 .621-.504 1.125-1.125 1.125h-9.75a1.125 1.125 0 01-1.125-1.125V7.875c0-.621.504-1.125 1.125-1.125H6.75a9.06 9.06 0 011.5.124m7.5 10.376h3.375c.621 0 1.125-.504 1.125-1.125V11.25c0-4.46-3.243-8.161-7.5-8.876a9.06 9.06 0 00-1.5-.124H9.375c-.621 0-1.125.504-1.125 1.125v3.5m7.5 10.375H9.375a1.125 1.125 0 01-1.125-1.125v-9.25m12 6.625v-1.875a3.375 3.375 0 00-3.375-3.375h-1.5" />
                 </svg>
                 Copy
              </button>

              <button 
                onClick={handleExportMarkdown}
                className="flex items-center gap-2 px-3 py-2 rounded-lg bg-white border border-slate-200 hover:bg-slate-50 hover:border-indigo-200 text-slate-600 transition-all text-sm font-medium"
                title="Download Markdown"
              >
                 <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
                 </svg>
                 Export MD
              </button>

              <div className="h-6 w-px bg-slate-200 mx-2 hidden sm:block"></div>

              <div className="flex items-center gap-2 relative group">
                <span className="text-xs font-bold uppercase tracking-wide text-slate-400">Translate:</span>
                <div className="flex bg-slate-100 rounded-lg p-1 gap-1">
                   {['English', 'Hindi', 'Spanish'].map(lang => (
                     <button
                       key={lang}
                       onClick={() => handleTranslate(lang)}
                       className={`
                         px-3 py-1 rounded-md text-xs font-medium transition-all
                         ${currentLang === lang 
                           ? 'bg-white text-indigo-600 shadow-sm' 
                           : 'text-slate-500 hover:text-slate-700'
                         }
                       `}
                     >
                       {lang}
                     </button>
                   ))}
                </div>
              </div>
           </div>

           {/* Related Concepts */}
           {relatedTopics && relatedTopics.length > 0 && (
             <div className="mt-8 animate-slide-up bg-slate-50/50 p-6 rounded-xl border border-slate-100">
               <h4 className="text-xs font-bold uppercase tracking-widest text-slate-400 mb-4">Related Topics</h4>
               <div className="flex flex-wrap gap-3">
                 {relatedTopics.map((topic, idx) => (
                   <button 
                    key={idx}
                    onClick={() => onTopicClick && onTopicClick(topic)}
                    className="px-4 py-2 rounded-lg border border-slate-200 bg-white hover:bg-indigo-50 hover:border-indigo-200 text-slate-600 hover:text-indigo-700 transition-all text-sm font-medium shadow-sm"
                   >
                     {topic}
                   </button>
                 ))}
               </div>
             </div>
           )}

        </div>
    </div>
  );
};